"""add chat events table

Revision ID: f9e51aa900fd
Revises: a23090d8aa0e
Create Date: 2026-09-12 14:36:08.732449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9e51aa900fd'
down_revision = 'a23090d8aa0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_chat_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('barbell_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tbl_chat_events_idx_conversation', 'tbl_chat_events', ['barbell_id', 'conversation_id', 'created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tbl_chat_events_idx_conversation', table_name='tbl_chat_events')
    op.drop_table('tbl_chat_events')
    # ### end Alembic commands ###
