"""add barbell tables

Revision ID: a23090d8aa0e
Revises: fe3425a78026
Create Date: 2026-09-12 14:06:12.143393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23090d8aa0e'
down_revision = 'fe3425a78026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_barbell_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('barbell_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('from_satellite_bps', sa.Integer(), nullable=False),
    sa.Column('to_satellite_bps', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decision_trace', sa.Text(), nullable=False),
    sa.Column('transaction_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tbl_barbell_actions_idx_barbell_id', 'tbl_barbell_actions', ['barbell_id'], unique=False)
    op.create_table('tbl_barbell_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('barbell_id', sa.UUID(), nullable=False),
    sa.Column('max_drawdown_bps', sa.Integer(), nullable=False),
    sa.Column('target_satellite_bps', sa.Integer(), nullable=False),
    sa.Column('max_satellite_bps', sa.Integer(), nullable=False),
    sa.Column('is_killed', sa.Boolean(), nullable=False),
    sa.Column('transaction_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tbl_barbell_policies_idx_barbell_id', 'tbl_barbell_policies', ['barbell_id'], unique=False)
    op.create_table('tbl_barbells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.Text(), nullable=False),
    sa.Column('owner_address', sa.Text(), nullable=False),
    sa.Column('anchor_asset_address', sa.Text(), nullable=False),
    sa.Column('satellite_asset_address', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address', name='tbl_barbells_ux_wallet_address')
    )
    op.create_index('tbl_barbells_idx_user_id', 'tbl_barbells', ['user_id'], unique=False)
    op.create_table('tbl_price_ticks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('asset_address', sa.Text(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('block_date', sa.DateTime(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'asset_address', 'block_number', name='tbl_price_ticks_ux_chain_asset_block')
    )
    op.create_index('tbl_price_ticks_idx_asset_date', 'tbl_price_ticks', ['asset_address', 'block_date'], unique=False)
    op.create_table('tbl_risk_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('barbell_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('total_value_usd', sa.Float(), nullable=False),
    sa.Column('anchor_value_usd', sa.Float(), nullable=False),
    sa.Column('satellite_value_usd', sa.Float(), nullable=False),
    sa.Column('cash_value_usd', sa.Float(), nullable=False),
    sa.Column('satellite_bps', sa.Integer(), nullable=False),
    sa.Column('peak_value_usd', sa.Float(), nullable=False),
    sa.Column('drawdown_bps', sa.Integer(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('momentum', sa.Float(), nullable=False),
    sa.Column('target_satellite_bps', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tbl_risk_snapshots_idx_barbell_date', 'tbl_risk_snapshots', ['barbell_id', 'snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tbl_risk_snapshots_idx_barbell_date', table_name='tbl_risk_snapshots')
    op.drop_table('tbl_risk_snapshots')
    op.drop_index('tbl_price_ticks_idx_asset_date', table_name='tbl_price_ticks')
    op.drop_table('tbl_price_ticks')
    op.drop_index('tbl_barbells_idx_user_id', table_name='tbl_barbells')
    op.drop_table('tbl_barbells')
    op.drop_index('tbl_barbell_policies_idx_barbell_id', table_name='tbl_barbell_policies')
    op.drop_table('tbl_barbell_policies')
    op.drop_index('tbl_barbell_actions_idx_barbell_id', table_name='tbl_barbell_actions')
    op.drop_table('tbl_barbell_actions')
    # ### end Alembic commands ###
